### ISSUE TITLE
Problema de logica

### ISSUE THREAD

**Issue by senjuana** [technovasoft/algoritmia#1]
//Bloque1
emmm carlos pides datos que no estas utilizando, no puedes pedir datos si no los vas a utilizar pense que en algun momento me hibas poner los datos que me pides ingrsar solo pides datos que no usas

**Comment by carloshdez31** [comment]
?????????

**Comment by senjuana** [comment]
yep en tu codigo solo pides datos que no utilizas ni imprimes

**Comment by carloshdez31** [comment]
Sigo sin entender lo que me comentas, Se supone que lo que es la parte de la teoria la pondría Kevin no?

**Comment by senjuana** [comment]
si we pero tu pides datos en tu algoritmo y nunca los presentas como lo haces con la tabla que pones abajo que no tiene nada que ver con los datos ingresados

**Comment by carloshdez31** [comment]
No los puse porque tu me dijiste que la parte de la teoria se la aventaría Kevin, por que no tienen que ver con los datos? se supone que se tiene que calcular los porcentajes que estan de acuerdo a todo, pero ahorita subo esa informacion, acabo de llegar, no estuve en mi casa we lo lamento si les falle esta vez, espero que puedan entender todos, y si tienen que bajarme calificacion we hazlo, entiendo que fracasé esta vez y no replicaré si lo haces

**Comment by azael18** [comment]
Sólo esta vez?! 7_________7

**Comment by CesarRiveraSC** [comment]
Que paso carlostian?

**Comment by senjuana** [comment]
señores este issue acaba de cerrarse.
